# Python Lab 01: Basic Tools of Linear Algebra
## Francesco Della Santa, Computational Linear Algebra for Large Scale Problems, Politecnico di Torino

In this Lab, we learn to work with numpy arays, building some basic functions and algorithms for linear algebra.
We also have a look at the main basic functions of the linear algebra sub-packages.

In [1]:
# ***** ATTENTION! *****
# If you want that the "%matplotlib widget" works, you need the package ipympl (pip install ipympl)
#
#
# MATPLOTLIB INTERACTIVE VISUALIZATION. REMOVE (OR COMMENT) IF YOU NEED TO PRINT THE NOTEBOOK AS A PDF, SOMETIMES IT DOES NOT WORK WELL...
# %matplotlib widget
#
#

from IPython.display import display  # to display variables in a "nice" way
import numpy as np

## Test Matrices

In the next cell, we define some test matrices and vectors. Use these arrays to test your functions.

In [2]:
np.random.seed(2023)

# TEST MATRICES/LIN. SYSTEMS
A1 = np.random.rand(4, 4) # matrice quadrata
print('********** Matrix A1 **********')
print(A1)
print('')

A2 = np.random.rand(3, 4) # matrice rettangolare
print('********** Matrix A2 **********')
print(A2)
print('')

A3 = A1.copy() # matrice quadrata
A3[:, 2] = 0 # last column to 0
print('********** Matrix A3 **********')
print(A3)
print('')

A4 = A1.copy() # matrice quadrata
A4[:,0] = 0 # first column to 0
print('********** Matrix A4 **********')
print(A4)
print('')

A5 = np.hstack([A4, A1])
A5 = A5[:, :5] # add the first column of A1 
print('********** Matrix A5 **********')
print(A5)
print('')

A6 = A5.copy()
A6[:, 3] = 0
print('********** Matrix A6 **********')
print(A6)
print('')

b1 = A1 @ np.ones((A1.shape[1], 1)) # vettore termini noti
print('********** Vector b1 **********')
print(b1)
print('N.B.: np.ones((A1.shape[1], 1)) is solution of the L.S.: A1x = b1')
print('')

b2 = A2 @ np.ones((A2.shape[1], 1))
print('********** Vector b2 **********')
print(b2)
print('N.B.: np.ones((A2.shape[1], 1)) is solution of the L.S.: A2x = b2')
print('')

b3 = b1.copy()
print('********** Vector b3 **********')
print(b3)
print('')

Ab1 = np.hstack([A1, b1])
print('********** Augmented Matrix of L.S. A1x = b1 **********')
print(Ab1)
print('')

Ab2 = np.hstack([A2, b2])
print('********** Augmented Matrix of L.S. A2x = b2 **********')
print(Ab2)
print('')

Ab3 = np.hstack([A3, b3])
print('********** Augmented Matrix of L.S. A3x = b3 **********')
print(Ab3)
print('')


********** Matrix A1 **********
[[0.3219883  0.89042245 0.58805226 0.12659609]
 [0.14134122 0.46789559 0.02208966 0.72727471]
 [0.52438734 0.54493524 0.45637326 0.50138226]
 [0.39446855 0.1511723  0.36087518 0.16207701]]

********** Matrix A2 **********
[[0.33795869 0.18032328 0.3909914  0.03564821]
 [0.56486165 0.20346149 0.32060446 0.37656378]
 [0.18405414 0.10395184 0.45492722 0.19586384]]

********** Matrix A3 **********
[[0.3219883  0.89042245 0.         0.12659609]
 [0.14134122 0.46789559 0.         0.72727471]
 [0.52438734 0.54493524 0.         0.50138226]
 [0.39446855 0.1511723  0.         0.16207701]]

********** Matrix A4 **********
[[0.         0.89042245 0.58805226 0.12659609]
 [0.         0.46789559 0.02208966 0.72727471]
 [0.         0.54493524 0.45637326 0.50138226]
 [0.         0.1511723  0.36087518 0.16207701]]

********** Matrix A5 **********
[[0.         0.89042245 0.58805226 0.12659609 0.3219883 ]
 [0.         0.46789559 0.02208966 0.72727471 0.14134122]
 [0.       

## Exercise 1: Computation of the Determinant

Fill in the missing parts of the **my_det** function of the following cell such that, for any square matrix $A\in\mathbb{R}^{n\times n}$, it returns the determinat of $A$, computed using the *Laplace Expansion*.

After you filled in the missing parts of **my_det** function, test it running the cell next to it. There, you can compare the determinat computed with **my_det** and the one of the function np.**linalg.det**. # built-in function to computing the determinat

### Recap: Determinant and Laplace Expansion
Remember the *First Laplace Theorem*:
\begin{equation*}
det(A) = \sum_{j=1}^n a_{ij}\alpha^{(i,j)} = \sum_{j=1}^n (-1)^{i+j} a_{ij} det(A^{(i,j)})\,,
\end{equation*}
for any fixed $i\in\{1,\ldots , n\}$ and where $A\in\mathbb{R}^{n\times n}$. We recall that:
1. $\alpha^{(i,j)}$ is the $(i,j)$-cofactor of $A$, i.e.: $$\alpha^{(i,j)}= (-1)^{i+j}det(A^{(i,j)})\,;$$
1. $A^{(i,j)}$ is the sub-matrix of $A$ obtained **removing** row $i$ and column $j$ (see the np.**delete** numpy function to delete rows/columns from a matrix).

Then, we can write a **recursive** algorithm to compute the determinant: # recursive--> the function calls itself inside the code.
- **my_det**($A\in\mathbb{R}^{n\times n}$, $i_{fix}$):
    1. det $\gets$ 0;
    1. **if** $A\in\mathbb{R}^{1\times 1}$:
        1. det $\gets$ $a_{11}$;
    1. **else**: 
        1. **if** $i_{fix} > n$ **do:**
            1. $i_{fix} \gets 1$ (*attention:* index 1 means "first row"!)
        1. **for** $j=1,\ldots ,n$ **do:**
            1. $A'$ $\gets$ $A^{(i_{fix}\, ,\,j)}$;
            1. $\alpha^{(i_{fix}, j)}$ $\gets$ $(-1)^{i_{fix} + j} \ $ my\_det($A' , i_{fix}$) (*attention:* recursion!);
            1. det $\gets$ det $+\ a_{i_{fix}j} \alpha^{(i_{fix}, j)}$ ;
    1. **return** det

In [3]:
# Function my_det

def my_det(A, i_fix=0):
    """
    Compute RECURSIVELY the determinant of a square matrix A using the 1st Laplace Th.
    :param A: 2D-array object (numpy ndarray), with shape (n, n)
    :param i_fix: index between 0 and n-1 (the removed row for Lap. Expansion)
    :return det: the determinant of the matrix
    """
    m, n = A.shape
    if m != n:
        print('THE MATRIX IS NOT SQUARE!')
        return None

    det = 0 # inizializzo il determinante
    if A.shape == (1, 1): # se sono arrivata all'ultima sottomatrice (con un solo elemento), il seterminante è l'elemento stesso
        det = A[0,0]  # DONE!!
        # if the matrix is actually a scalar, the determinant is the scalar itself!
    else:
        if i_fix >= m: # condizione terminale quando solo arrivata all'ultima riga 
            i_fix = 0   # DONE!! # rifisso la riga fissata a zero
        for j in range(A.shape[1]): # mi muovo su tutte le colonne
            # trovo le sottomatrici
            Aij = np.delete(A, i_fix, axis=0)  # DONE!! # elimino prima la riga
            Aij = np.delete(Aij, j, axis=1)  # DONE!!  # elimino poi la colonna
            # write above one or more lines of code to compute A^(i,j); use the np.delete function.

            # N.B.: The parity of the exponent (i_fix + j) does not change with the 0-index convention of numpy.
            # Indeed, (i_fix + j) = ((real_i_fix - 1) + (real_j - 1)) = (real_i_fix + real_j - 2) 
            # --> parity does not change!
            # trovo il cofattore
            alphaij = (-1) ** (i_fix + j) * my_det(Aij, i_fix)  # RECURSIVE CALL OF THE FUNCTION!
            # aggiorno il determinante
            det += A[i_fix, j]*alphaij # DONE!! 

    return det

In [4]:
# TEST THE my_det FUNCTION

print(f'Determinant of A1: {my_det(A1, 0)} (my_det)')
print(f'Determinant of A1: {np.linalg.det(A1)} (np.linalg.det)')
print('')
print(f'Determinant of A2: {my_det(A2, 0)} (my_det)')
print(f'Determinant of A2: "LinAlgError: Last 2 dimensions of the array must be square" (np.linalg.det)')
print('')
print(f'Determinant of A3: {my_det(A3, 0)} (my_det)')
print(f'Determinant of A3: {np.linalg.det(A3)} (np.linalg.det)')

Determinant of A1: -0.008346534048340178 (my_det)
Determinant of A1: -0.008346534048340177 (np.linalg.det)

THE MATRIX IS NOT SQUARE!
Determinant of A2: None (my_det)
Determinant of A2: "LinAlgError: Last 2 dimensions of the array must be square" (np.linalg.det)

Determinant of A3: 0.0 (my_det)
Determinant of A3: 0.0 (np.linalg.det)


## Exercise 2: Gaussian Elimination - Row Echelon Form

Fill in the missing parts of the **my_gauss** function in the following cell such that, for any matrix $A\in\mathbb{R}^{m\times n}$, it returns a row echelon form $A'$ of $A$, through the Gaussian elimination algorithm.

After you filled in the missing parts of **my_gauss** function, test it running the cell next to it. There, you can also **compare the rank** computed with **my_gauss** and the one of the function np.**linalg.matrix_rank**.

### Recap: Gaussian Elimination Algorithm (Idea)

1. Select the first column (i.e., $j=1$) as working column;
1. Select the first row (i.e., $k=1$) as row of the next pivot;
1. Look for the element with maximum absolute value in column $j$, among rows $i=k,\ldots ,n$;
1. if the element with max. abs. val. is zero, skip to step 5; otherwise:
    1. swap the row of that element with row $k$;
    1. add to each row $i=k+1,\ldots ,n$ the row $i$ multiplied by $-(a_{ij}\,/\,a_{kj})$ (i.e., set to zero all the entries under the pivot);
    1. increase the pivot index $k$ by one;
1. move to the next column (i.e., increase $j$ by one)
1. if $j>n$ (i.e., there are no more columns) or $k>n$ (i.e., there are no more rows), stop; otherwise, repeat from step 3.
    
### Recap: Gaussian Elimination Algorithm (Pseudo-code)

- **my_gauss**($A\in\mathbb{R}^{m\times n}$):
    1. $k\gets 1$ (pivot index);
    1. $j\gets 1$ (column index);
    1. **while** $k\leq m$ and $j\leq n$ **do**: (i.e., stop when columns/rows are finished)
        1. $\widehat{a}\gets$ element of the sub-column $A_{(k,\ldots ,m), j}$ with maximum absolute value;
        1. $\widehat{i}\gets$ row-index of $\widehat{a}$, i.e.such that $\widehat{a}=A_{\widehat{i},j}$;
        1. **if** $\widehat{a}\neq 0$ **do:**
            1. *swap* row $k$ and row $\widehat{i}$ in $A$;
            1. **for** $i=(k+1),\ldots, m$ **do:**
                1. *add* to row $A_{i,\cdot}$ the row-vector $-(\frac{a_{ij}}{\widehat{a}})A_{k,\cdot}$ (i.e., set to zero all the entries under $a_{k,j}$);
            1. $k\gets k+1$;
        1. $j\gets j+1$;
    1. **return** $A$ (now in row echelon form)
    
#### ATTENTION: Zeros and Tolerance Values in Numerical Computations
Performing numerical computations, exact zero values are very rare to be obtained. Then, in the code of a program, it is important to "translate" any check w.r.t. a zero value introducing an arbitrary (small) tolerance.

**Example:** $x = 0 \rightsquigarrow |x|\leq \textit{tolerance value}$.

#### ATTENTION: Array operations
Many operations that are written as **for** cycles in the pseudo-codes can be written in the python code exploiting the array operations! Then, **avoid using "for"** if you can do the same operation with arrays; ideed, **these operations are much faster**!

### Suggestions:
Read the documentation or the help of these functions/methods, that can be useful in the exercise:
1. np.**abs**;
2. v.**argmax** (method of a generic array v).

In [5]:
def my_gauss(M, tol=1e-8):
    """
    Function that compute the row echelon form of a given matrix M.
    :param M: 2D-array object (numpy ndarray)
    :param tol: tolerance for setting to zero the numerical zeros for computing Around
    :return A: 2D-array object (numpy ndarray) representing the row echelon form of M
    :return Around: The matrix A where values under the tolerance are set to zeros (to obtain a "real" row echelon form)
    :return rank: return the rank of M (computed exploiting the row echelon form A)
    """

    A = M.copy()
    m, n = A.shape

    k = 0  # pivot index
    j = 0  # column index
    
    # ATTENTION!: remember the 0-indexing convention of Python!
    while k < m and j < n:
        # rows corresponding to max abs in columns
        row_maxabsel = k + np.abs(A[k:, j]).argmax(axis=0) # mi dà l'indice della riga dove c'è l'elemento con val ass max 
        
        # max abs value in column
        maxabsel = A[row_maxabsel, j]

        # Swap "maximum-abs-row" (row_maxabsel) with row k and
        # perform operations to put as 0 all the entries below entry of position (k,j)
        if np.abs(maxabsel) >= tol:  # DONE!! (insert the check on maxabsel not zero... using the tolerance!)
            # Swapping
            kth_row = A[k, :].copy() # devo fare la copia altrimenti modifico direttamente su A
            max_row = A[row_maxabsel,:].copy() # DONE!!
            A[k, :] = max_row # scambio la riga con l'elemento con val assoluto max e diventa la riga corrente del pivot
            A[row_maxabsel,:] = kth_row
            # write above one or more lines of code to complete the swap between rows.
            
            # Zeros: DO NOT USE A for!!!
            factor_vec = np.array(A[(k + 1):, j] / maxabsel, ndmin=2).T # vettore colonna dei fattori moltiplicativi
            A[(k+1):, :] = A[(k+1):, :] - factor_vec * A[k, :] # DONE!! # faccio diventare 0 tutti i valori sotto al pivot
            # complete the line above to build a column vector with the coefficients a_ij/maxabsel 
            # necessary to set to zero the elements under the pivot.
            k += 1 # mando avanti la riga corrente del pivot solo se ho trovato elementi non nulli

        j += 1 # in ogni caso passo alla colonna successiva per la ricrca del pivot 

    Around = A.copy()
    # For aesthetic reasons only:
    Around[np.abs(A) < tol] = 0
    
    # RANK COMPUTATION
    smallest_axis = np.argmin(Around.shape)  # case m == n --> returns 0 ('rows')
    nonzero_axis = Around.nonzero()[smallest_axis]
    rank = np.unique(nonzero_axis).size

    return A, Around, rank

In [6]:
# TEST THE my_gauss FUNCTION

EA1, EA1tol, rankA1 = my_gauss(A1, tol=1e-8)
print(f'Row Echelon Form of A1 (my_gauss_rank={rankA1}, numpy_rank={np.linalg.matrix_rank(A1)}):')
print(EA1tol)
print('')

EA2, EA2tol, rankA2 = my_gauss(A2, tol=1e-8)
print(f'Row Echelon Form of A2 (my_gauss_rank={rankA2}, numpy_rank={np.linalg.matrix_rank(A2)}):')
print(EA2tol)
print('')

EA3, EA3tol, rankA3 = my_gauss(A3, tol=1e-8)
print(f'Row Echelon Form of A3 (my_gauss_rank={rankA3}, numpy_rank={np.linalg.matrix_rank(A3)}):')
print(EA3tol)
print('')

EAb1, EAb1tol, rankAb1 = my_gauss(Ab1, tol=1e-8)
print(f'Row Echelon Form of Ab1 (my_gauss_rank={rankAb1}, numpy_rank={np.linalg.matrix_rank(Ab1)}):')
print(EAb1tol)
print('')

EAb2, EAb2tol, rankAb2 = my_gauss(Ab2, tol=1e-8)
print(f'Row Echelon Form of Ab2 (my_gauss_rank={rankAb2}, numpy_rank={np.linalg.matrix_rank(Ab2)}):')
print(EAb2tol)
print('')

EAb3, EAb3tol, rankAb3 = my_gauss(Ab3, tol=1e-8)
print(f'Row Echelon Form of Ab3 (my_gauss_rank={rankAb3}, numpy_rank={np.linalg.matrix_rank(Ab3)}):')
print(EAb3tol)
print('')

EA4, EA4tol, rankA4 = my_gauss(A4, tol=1e-8)
print(f'Row Echelon Form of A4 (my_gauss_rank={rankA4}, numpy_rank={np.linalg.matrix_rank(A4)}):')
print(EA4tol)
print('')

EA5, EA5tol, rankA5 = my_gauss(A5, tol=1e-8)
print(f'Row Echelon Form of A5 (my_gauss_rank={rankA5}, numpy_rank={np.linalg.matrix_rank(A5)}):')
print(EA5tol)
print('')

EA6, EA6tol, rankA6 = my_gauss(A6, tol=1e-8)
print(f'Row Echelon Form of A6 (my_gauss_rank={rankA6}, numpy_rank={np.linalg.matrix_rank(A6)}):')
print(EA6tol)
print('')

Row Echelon Form of A1 (my_gauss_rank=4, numpy_rank=4):
[[ 0.52438734  0.54493524  0.45637326  0.50138226]
 [ 0.          0.55581717  0.30782648 -0.18126646]
 [ 0.          0.         -0.27870659  0.69682586]
 [ 0.          0.          0.          0.10274833]]

Row Echelon Form of A2 (my_gauss_rank=3, numpy_rank=3):
[[ 0.56486165  0.20346149  0.32060446  0.37656378]
 [ 0.          0.05859156  0.19917264 -0.18965121]
 [ 0.          0.          0.22245586  0.19505106]]

Row Echelon Form of A3 (my_gauss_rank=3, numpy_rank=3):
[[ 0.52438734  0.54493524  0.          0.50138226]
 [ 0.          0.55581717  0.         -0.18126646]
 [ 0.          0.          0.          0.69682586]
 [ 0.          0.          0.          0.        ]]

Row Echelon Form of Ab1 (my_gauss_rank=4, numpy_rank=4):
[[ 0.52438734  0.54493524  0.45637326  0.50138226  2.02707811]
 [ 0.          0.55581717  0.30782648 -0.18126646  0.68237719]
 [ 0.          0.         -0.27870659  0.69682586  0.41811927]
 [ 0.          0.  

## Exercise 3: Gaussian Elimination - Reduced Row Echelon Form

Fill in the missing parts of the **my_reduced_gauss** function of the following cell such that, for any matrix $A\in\mathbb{R}^{m\times n}$, it returns a *reduced* row echelon form $A'$ of $A$, through a "modified" Gaussian elimination algorithm.

After you filled in the missing parts of **my_reduced_gauss** function, test it running the cell next to it.

### Suggestions for the Exercise:
The Gaussian elimination algorithm for the reduced row echelon form is very similar to the "classic" Gaussian elimination. You just need to:
1. Set to zero also the elements above the pivots;
1. Once obtained a row echelon form with zeros both above and under the pivots, set to 1 the pivots.

In [7]:
def my_reduced_gauss(M, tol=1e-8):
    """
    Function that compute the reduced row echelon form of a given matrix M.
    :param M: 2D-array object (numpy ndarray)
    :param tol: tolerance for setting to zero the numerical zeros for computing Around
    :return A: 2D-array objects (numpy ndarray) representing the red. row echelon form of M
    :return Around: The matrix A where numerical zeros are set to zero
    :return rank: return the rank of M (computed exploiting the row echelon form A)
    """

    A = M.copy()
    m, n = A.shape
    
    k = 0
    j = 0
    
    piv_inds = []  # list for pivot indexes
    
    while k < m and j < n:
        row_maxabsel = k + np.abs(A[k:, j]).argmax(axis=0)
        maxabsel = A[row_maxabsel, j]
        # Swap "maximum-abs-row" (row_maxabsel) with row k and
        # perform operations to put as 0 all the entries below entry of position (k,j)
        if np.abs(maxabsel) >= tol: 
            # Swapping
            kth_row = A[k, :].copy() 
            max_row = A[row_maxabsel,:].copy()
            A[k, :] = max_row 
            A[row_maxabsel,:] = kth_row
            
            # Zeros: DO NOT USE A for!!!
            factor_vec = np.array(A[(k + 1):, j] / maxabsel, ndmin=2).T 
            A[(k+1):, :] = A[(k+1):, :] - factor_vec * A[k, :]

            # annullo anche i valori sopra il pivot (tranne quando il pivot è nella prima riga)
            if k > 0:
                factor_above = np.array(A[:k, j] / maxabsel, ndmin=2).T  # shape (k,1)
                A[:k, :] = A[:k, :] - factor_above * A[k, :] # tutti i valori nella stessa colonna del pivot ma nelle righe sopra diventano 0
                
            # store pivot coordinates (current pivot is at (k, j))
            piv_inds.append((k, j)) # mi salvo le coordinate del pivot
            
            k += 1 
        j += 1
        # DONE!!
        # complete the while block, copying the block in my_gauss but adding the 
        # part where also the elements above the pivot are set to zero.
        # Use the lists piv_inds to store the coordinates of the pivot in the matrix.

    # MAKING OTHER GAUSS OPERATIONS FOR SETTING PIVOTS EQUAL TO 1
    for ii in range(len(piv_inds)):
        pivot_ii = A[piv_inds[ii][0], piv_inds[ii][1]] # prendo il valore del pivot alla posizione salvata in piv_inds[ii]
        #if np.abs(pivot_ii) > tol:
        # NORMALIZZAZIONE: divido tutta la riga pivot per il valore del pivot
        # così il pivot diventa esattamente 1
        A[piv_inds[ii][0], :] =  A[piv_inds[ii][0], :] / pivot_ii # DONE!!
        #else:
            # nel raro caso numerico in cui il pivot sia ~0, non dividere
            #A[piv_inds[ii][0], :] = A[piv_inds[ii][0], :]
            
    Around = A.copy()
    # For aesthetic reasons only:
    Around[abs(A) < tol] = 0

    # RANK COMPUTATION
    smallest_axis = np.argmin(Around.shape)  # case m == n --> returns 0 ('rows')
    nonzero_axis = Around.nonzero()[smallest_axis]
    rank = np.unique(nonzero_axis).size

    return A, Around, rank

In [8]:
# TEST THE my_reduced_gauss FUNCTION

rEA1, rEA1tol, rankA1 = my_reduced_gauss(A1, tol=1e-8)
print(f'Reduced Row Echelon Form of A1 (my_gauss_rank={rankA1}, numpy_rank={np.linalg.matrix_rank(A1)}):')
print(rEA1tol)
print('')

rEA2, rEA2tol, rankA2 = my_reduced_gauss(A2, tol=1e-8)
print(f'Row Echelon Form of A2 (my_gauss_rank={rankA2}, numpy_rank={np.linalg.matrix_rank(A2)}):')
print(rEA2tol)
print('')

rEA3, rEA3tol, rankA3 = my_reduced_gauss(A3, tol=1e-8)
print(f'Row Echelon Form of A3 (my_gauss_rank={rankA3}, numpy_rank={np.linalg.matrix_rank(A3)}):')
print(rEA3tol)
print('')

rEAb1, rEAb1tol, rankAb1 = my_reduced_gauss(Ab1, tol=1e-8)
print(f'Row Echelon Form of Ab1 (my_gauss_rank={rankAb1}, numpy_rank={np.linalg.matrix_rank(Ab1)}):')
print(rEAb1tol)
print('')

rEAb2, rEAb2tol, rankAb2 = my_reduced_gauss(Ab2, tol=1e-8)
print(f'Row Echelon Form of Ab2 (my_gauss_rank={rankAb2}, numpy_rank={np.linalg.matrix_rank(Ab2)}):')
print(rEAb2tol)
print('')

rEAb3, rEAb3tol, rankAb3 = my_reduced_gauss(Ab3, tol=1e-8)
print(f'Row Echelon Form of Ab3 (my_gauss_rank={rankAb3}, numpy_rank={np.linalg.matrix_rank(Ab3)}):')
print(rEAb3tol)
print('')

rEA4, rEA4tol, rankA4 = my_reduced_gauss(A4, tol=1e-8)
print(f'Row Echelon Form of A4 (my_gauss_rank={rankA4}, numpy_rank={np.linalg.matrix_rank(A4)}):')
print(rEA4tol)
print('')

rEA5, rEA5tol, rankA5 = my_reduced_gauss(A5, tol=1e-8)
print(f'Row Echelon Form of A5 (my_gauss_rank={rankA5}, numpy_rank={np.linalg.matrix_rank(A5)}):')
print(rEA5tol)
print('')

rEA6, rEA6tol, rankA6 = my_reduced_gauss(A6, tol=1e-8)
print(f'Row Echelon Form of A6 (my_gauss_rank={rankA6}, numpy_rank={np.linalg.matrix_rank(A6)}):')
print(rEA6tol)
print('')

Reduced Row Echelon Form of A1 (my_gauss_rank=4, numpy_rank=4):
[[1. 0. 0. 0.]
 [0. 1. 0. 0.]
 [0. 0. 1. 0.]
 [0. 0. 0. 1.]]

Row Echelon Form of A2 (my_gauss_rank=3, numpy_rank=3):
[[ 1.          0.          0.          2.40847893]
 [ 0.          1.          0.         -6.21740316]
 [ 0.          0.          1.          0.87680791]]

Row Echelon Form of A3 (my_gauss_rank=3, numpy_rank=3):
[[1. 0. 0. 0.]
 [0. 1. 0. 0.]
 [0. 0. 0. 1.]
 [0. 0. 0. 0.]]

Row Echelon Form of Ab1 (my_gauss_rank=4, numpy_rank=4):
[[1. 0. 0. 0. 1.]
 [0. 1. 0. 0. 1.]
 [0. 0. 1. 0. 1.]
 [0. 0. 0. 1. 1.]]

Row Echelon Form of Ab2 (my_gauss_rank=3, numpy_rank=3):
[[ 1.          0.          0.          2.40847893  3.40847893]
 [ 0.          1.          0.         -6.21740316 -5.21740316]
 [ 0.          0.          1.          0.87680791  1.87680791]]

Row Echelon Form of Ab3 (my_gauss_rank=4, numpy_rank=4):
[[1. 0. 0. 0. 0.]
 [0. 1. 0. 0. 0.]
 [0. 0. 0. 1. 0.]
 [0. 0. 0. 0. 1.]]

Row Echelon Form of A4 (my_gauss_ra

## Exercise 4: Reduced Row Echelon Form and Linear Systems

given a non singular (i.e., invertible) square matrix $A\in\mathbb{R}^{n\times n}$ and a vector $\boldsymbol{b}\in\mathbb{R}^n$, if the linear system $A\boldsymbol{x}=\boldsymbol{b}$ has *one unique* solution, the solution can be computed selecting the last column of the *reduced row echelon form* to the augmented matrix $A|\boldsymbol{b}\in\mathbb{R}^{n\times(n+1)}$.

Fill in the missing code of the function **my_gauss_solver** in the following cell. 

After you filled in the missing parts, test it running the cell next to it. There, you can also compare the solution computed with **my_gauss_solver** and the one of the function np.**linalg.solve**.

In [9]:
def my_gauss_solver(A, b, tol=1e-8): # per matrici quadrate
    """
    Compute the solution of Ax=b if A invertible.
    Otherwise it returns informations about the linear system
    :param A: 2D-array object (numpy ndarray) of shape (m, n)
    :param b: 2D-array object (numpy ndarray) of shape (m, 1)
    :param tol: tolerance for setting to zero the numerical zeros for computing Abround_gauss
    :return num_sol: None, 1 or infinity
    :return inf_power:None, 0 or "columns-of-A - rank(A)"
    :return x: None or unique solution of Ax=b (if num_sol==1)
    :return Ab_gauss, Abround_gauss: outputs of my_reduced_gauss(Ab, tol)
    :return rankA, rankAb: ranks of A and Ab
    """
    Ab = np.hstack([A, b]) # faccio la matrice aumentata aggiungendo la colonna dei termini noti
    Ab_gauss, Abround_gauss, rankAb = my_reduced_gauss(Ab, tol)  # DONE!
    _, _, rankA = my_reduced_gauss(A, tol) # DONE!

    # Ab_gauss = matrice in Reduced Row Echelon Form (RREF) ottenuta (con valori floating).
    # Abround_gauss = stessa matrice ma con valori piccoli (|val| < tol) messi esattamente a 0 (utile per pulire rumore numerico).
    # rankAb = rango della matrice aumentata (calcolato dalla RREF).
    
    if A.shape[0] != A.shape[1]: # se la matrice non è quadrata
        print('MATRIX IS NOT SQUARE!')
    elif rankA != rankAb: # se il rango della matrice A e della matrice aumentata Ab non è lo stesso non ho soluzioni
        # sistema inconsistente
        print('NO SOLUTIONS FOR THIS LINEAR SYSTEM')
        num_sol = None
        inf_power = None
        x = None
    else:
        inf_power = A.shape[1] - rankA # numero di soluzioni è uguale oo^(n-rkA) # numero di colonne libere
        num_sol = np.inf ** inf_power  # it is 1 if inf_power = 0, it is np.inf otherwise
        if num_sol == 1: # se c'è un'unica soluzione
            print('ONE UNIQUE SOLUTION FOR THIS LINEAR SYSTEM')
            # x è data dalla ultima colonna della RREF di Ab # con reshape la rendo colonna
            x = Ab_gauss[:, -1].reshape(-1, 1)  # DONE!
        else:
            print(f'INFINITE ** {inf_power} SOLUTIONS FOR THIS LINEAR SYSTEM')
            x = None

    return num_sol, inf_power, x, Ab_gauss, Abround_gauss, rankA, rankAb

In [10]:
# TEST THE my_gauss_solver FUNCTION

print(f'***** SOLUTION OF A1 x = b1 ***** ')
_, _, x1, _, _, _, _ = my_gauss_solver(A1, b1, tol=1e-8)
print('my_gauss_solver solution:')
print(x1)
print('numpy.linalg.solve solution:')
print(np.linalg.solve(A1, b1))
print('')

print(f'***** SOLUTION OF A3 x = b3 ***** ')
_, _, x3, _, _, _, _ = my_gauss_solver(A3, b3, tol=1e-8)
print('my_gauss_solver solution:')
print(x3)
print('numpy.linalg.solve solution:')
try:
    print(np.linalg.solve(A3, b3))
except:
    print('LinAlgError: Singular matrix')
print('')

***** SOLUTION OF A1 x = b1 ***** 
ONE UNIQUE SOLUTION FOR THIS LINEAR SYSTEM
my_gauss_solver solution:
[[1.]
 [1.]
 [1.]
 [1.]]
numpy.linalg.solve solution:
[[1.]
 [1.]
 [1.]
 [1.]]

***** SOLUTION OF A3 x = b3 ***** 
NO SOLUTIONS FOR THIS LINEAR SYSTEM
my_gauss_solver solution:
None
numpy.linalg.solve solution:
LinAlgError: Singular matrix



## Exercise 4b: Reduced Row Echelon Form and Non-Square Linear Systems

Given a matrix $A\in\mathbb{R}^{m\times n}$ and a vector $\boldsymbol{b}\in\mathbb{R}^m$, if the linear system $A\boldsymbol{x}=\boldsymbol{b}$ has a solution, the solution can be computed looking at the last column of the *reduced row echelon form* of the augmented matrix $A|\boldsymbol{b}\in\mathbb{R}^{m\times(n+1)}$ and at the indexes of the pivots.

Fill in the missing code of the function **my_general_gauss_solver** in the following cell, remaing it as **my_general_gauss_solver**.



After you filled in the missing parts, test it running the cell next to it. There, you can also compare the solution computed with **my_gauss_solver** and the one of the function np.**linalg.solve**.

In [11]:
def my_gauss_solver(A, b, tol=1e-8): # per matrici anche non quadrate
    """
    Compute the solution of Ax=b, if it exists.
    Otherwise it returns informations about the linear system
    :param A: 2D-array object (numpy ndarray) of shape (m, n)
    :param b: 2D-array object (numpy ndarray) of shape (m, 1)
    :param tol: tolerance for setting to zero the numerical zeros for computing Abround_gauss
    :return num_sol: None, 1 or infinity
    :return inf_power:None, 0 or "columns-of-A - rank(A)"
    :return x: None or unique solution of Ax=b (if num_sol==1)
    :return Ab_gauss, Abround_gauss: outputs of my_reduced_gauss(Ab, tol)
    :return rankA, rankAb: ranks of A and Ab
    :return x_particular: equal to x or a particular solution of Ax=b (if num_sol>1)
    """
    
    m, n = A.shape
    # INITIALIZATIONS...  # DONE!
    Ab = np.hstack([A, b])
    Ab_gauss, Abround_gauss, rankAb = my_reduced_gauss(Ab, tol)
    _, _, rankA = my_reduced_gauss(A, tol)

    # Ab_gauss = matrice in Reduced Row Echelon Form (RREF) ottenuta (con valori floating).
    # Abround_gauss = stessa matrice ma con valori piccoli (|val| < tol) messi esattamente a 0 (utile per pulire rumore numerico).
    # rankAb = rango della matrice aumentata (calcolato dalla RREF).

    if rankA != rankAb: # Se il rango della aumentata è maggiore del rango di A, il sistema è inconsistente
        print('NO SOLUTIONS FOR THIS LINEAR SYSTEM')
        num_sol = None
        inf_power = None
        x = None
        x_particular = None
    else:        
        inf_power = n - rankA
        num_sol = np.inf ** inf_power  # it is 1 if inf_power = 0, it is np.inf otherwise
        if num_sol == 1: # soluzione unica
            x = Ab_gauss[:, -1].reshape(m, 1) # equivale all'ultima colonna della matrice aumentata dopo che ho ridotto
            x_particular = x.copy() # faccio la copia
            print('ONE UNIQUE SOLUTION FOR THIS LINEAR SYSTEM')
            if m > n:
                # anche se m>n può esserci una soluzione unica se rankA == n (A ha rango massimo). 
                # In tal caso le righe non-nulle della RREF possono non essere le prime n righe;
                print('MATRIX IS NOT SQUARE!')
                # prende le righe con almeno un elemento non-zero: i primi n di queste contengono i valori delle incognite (le righe pivot).
                nonzero_rows = np.unique(Abround_gauss.nonzero()[0])
                # prendo le ultime colonne corrispondenti ai pivot non-zero rows
                x = Abround_gauss[nonzero_rows[:n], -1].reshape(n, 1)  # DONE!
                x_particular = x.copy()
            else:  # ONLY SQUARE CASE, IMPOSSIBLE TO HAVE m < n IF num_sol == 1
                print('(SQUARE MATRIX)')
            print('')
        else:
            print(f'INFINITE ** {inf_power} SOLUTIONS FOR THIS LINEAR SYSTEM')
            print('')
            x = None
            # Identifico le colonne non-nulle (escludendo la colonna di termini noti)
            nonzero_cols = np.unique(Abround_gauss[:, :-1].nonzero()[1])
            pivot_cols = nonzero_cols[:rankA] # colonne di A che contengono pivot
            pivot_rows = np.unique(Abround_gauss[:, pivot_cols].nonzero()[0]) # ottiene le righe pivot corrispondenti.
            x_particular = np.zeros((n, 1))
            # Costruisco un x_particular inizializzato a zero e riempio le voci corrispondenti alle colonne pivot con i valori trovati nell'ultima colonna (termini noti) alle righe pivot
            # assegno alle colonne pivot i valori della colonna dei termini noti (righe pivot)
            x_particular[pivot_cols] = Abround_gauss[pivot_rows, -1].reshape(-1, 1)  # DONE!
            # Questo assegna una soluzione particolare: le variabili pivot vengono fissate ai valori che compaiono nella RREF, mentre le variabili libere rimangono zero. È una scelta standard per costruire una soluzione particolare.
    return num_sol, inf_power, x, Ab_gauss, Abround_gauss, rankA, rankAb, x_particular

In [12]:
# TEST THE my_gauss_solver FUNCTION

print(f'***** SOLUTION OF A1 x = b1 ***** ')
_, _, x1, _, A1b1_gauss, _, _, _ = my_gauss_solver(A1, b1, tol=1e-8)
print('my_gauss_solver solution:')
print(x1)
print('numpy.linalg.solve solution:')
print(np.linalg.solve(A1, b1))
print('(A|b) matrix:')
print(A1b1_gauss)
print('')

print(f'***** SOLUTION OF A2 x = b2 ***** ')
_, _, x2, _, A2b2_gauss, _, _, x2_particular = my_gauss_solver(A2, b2, tol=1e-8)
print('my_gauss_solver solution:')
print(x2)
print('my_gauss_solver particular solution:')
print(x2_particular)
print('(A|b) matrix:')
print(A2b2_gauss)
print('')

print(f"***** SOLUTION OF (A2^T) x = b2' *****")
b2b = (A2.T).sum(axis=1, keepdims=True)
_, _, x2b, _, A2Tb2b_gauss, _, _, _ = my_gauss_solver(A2.T, b2b, tol=1e-8)
print('my_gauss_solver solution:')
print(x2b)
print('(A|b) matrix:')
print(A2Tb2b_gauss)
print('')

print(f'***** SOLUTION OF A3 x = b3 ***** ')
_, _, x3, _, _, _, _, _ = my_gauss_solver(A3, b3, tol=1e-8)
print('my_gauss_solver solution:')
print(x3)
print('numpy.linalg.solve solution:')
try:
    print(np.linalg.solve(A3, b3))
except:
    print('LinAlgError: Singular matrix')
print('')

print(f'***** SOLUTION OF A6 x = b6 ***** ')
_, _, x6, _, A6b6_gauss, _, _, x6_particular = my_gauss_solver(A6, A6 @ np.ones((A6.shape[1], 1)), tol=1e-8)
print('my_gauss_solver solution:')
print(x6)
print('my_gauss_solver particular solution:')
print(x6_particular)
print('(A|b) matrix:')
print(A6b6_gauss)
print('')

***** SOLUTION OF A1 x = b1 ***** 
ONE UNIQUE SOLUTION FOR THIS LINEAR SYSTEM
(SQUARE MATRIX)

my_gauss_solver solution:
[[1.]
 [1.]
 [1.]
 [1.]]
numpy.linalg.solve solution:
[[1.]
 [1.]
 [1.]
 [1.]]
(A|b) matrix:
[[1. 0. 0. 0. 1.]
 [0. 1. 0. 0. 1.]
 [0. 0. 1. 0. 1.]
 [0. 0. 0. 1. 1.]]

***** SOLUTION OF A2 x = b2 ***** 
INFINITE ** 1 SOLUTIONS FOR THIS LINEAR SYSTEM

my_gauss_solver solution:
None
my_gauss_solver particular solution:
[[ 3.40847893]
 [-5.21740316]
 [ 1.87680791]
 [ 0.        ]]
(A|b) matrix:
[[ 1.          0.          0.          2.40847893  3.40847893]
 [ 0.          1.          0.         -6.21740316 -5.21740316]
 [ 0.          0.          1.          0.87680791  1.87680791]]

***** SOLUTION OF (A2^T) x = b2' *****
ONE UNIQUE SOLUTION FOR THIS LINEAR SYSTEM
MATRIX IS NOT SQUARE!

my_gauss_solver solution:
[[1.]
 [1.]
 [1.]]
(A|b) matrix:
[[1. 0. 0. 1.]
 [0. 1. 0. 1.]
 [0. 0. 1. 1.]
 [0. 0. 0. 0.]]

***** SOLUTION OF A3 x = b3 ***** 
NO SOLUTIONS FOR THIS LINEAR SYSTE