# Python Lab 02: Orthogonalization Methods
## Francesco Della Santa, Computational Linear Algebra for Large Scale Problems, Politecnico di Torino

In this lesson, we will implement the (Modified) *Gram-Schmidt* method, the *Givens* method and the *House-
holder* method.

In [1]:
# ***** ATTENTION! *****
# If you want that the "%matplotlib widget" works, you need the package ipympl (pip install ipympl)
#
#
# MATPLOTLIB INTERACTIVE VISUALIZATION. REMOVE (OR COMMENT) IF YOU NEED TO PRINT THE NOTEBOOK AS A PDF, SOMETIMES IT DOES NOT WORK WELL...
%matplotlib widget
#
#

from IPython.display import display  # to display variables in a "nice" way
import numpy as np
import matplotlib.pyplot as plt
import pandas as pd
from testmatrices import A1, b1, Ab1

## The Gram-Schmidt Method

Given an invertible square matrix $X\in\mathbb{R}^{n\times n}$, the Gram-Schmidt (GS) method compute two matrices, $Q, R \in\mathbb{R}^{n\times n}$, such that:
- $Q$ is orthogonal (i.e., $QQ^\top = \mathbb{I}_n = Q^{\top}Q$);
- The columns $\{\boldsymbol{q}_1,\ldots ,\boldsymbol{q}_n\}$ of $Q$ are an orthonormal base of the space $\langle \boldsymbol{x}_1,\ldots ,\boldsymbol{x}_n\rangle$ generated by the columns of $X$ (obvious if $X$ is square, but not if we considere the "extended case" $X\in\mathbb{R}^{m\times n}$, $m > n$);
- $R\in\mathbb{R}^{n\times n}$ upper triangular;
- $QR=X$.


#### Description of the GS Method

The idea of the GS method is to *build* iteratively the columns of $Q$ from the columns of $X$. In particular, we compute the column $\boldsymbol{q}_j$ as the column $\boldsymbol{x}_j$ from which we subtract the previous columns of $Q$ multiplied by their projection onto $\boldsymbol{x}_j$ (because we want orthogonal columns for $Q$); then, we normalize the result of this operation. The element $r_{ij}$, with $i< j$, are the projections of $\boldsymbol{q}_i$ on $\boldsymbol{x}_j$, while $r_{jj}$ is the norm of $\boldsymbol{q}_j$ *before the normalization step*.

From a "pseudocode point-of-view":
1. **for** $j=1,\ldots , n$ **do:**
    1. $\boldsymbol{q}_j\gets \boldsymbol{x}_j - \sum_{i=1}^{j-1}(\boldsymbol{x}_j,\boldsymbol{q}_i) \boldsymbol{q}_i$, where$(\boldsymbol{x}_j,\boldsymbol{q}_i)$ becomes $r_{ij}$;
    1. $\boldsymbol{q}_j\gets \frac{\boldsymbol{q}_j}{||\boldsymbol{q}_j||}$, where $||\boldsymbol{q}_j||$ becomes $r_{jj}$.

#### Exercise 1: GS Method

Complete the function in the following cell, such that it performs the GS method for any square matrix. The function must return not only $Q$ and $R$, but also the following norms representing the quality of the outputs:
- $||\mathbb{I}_n - QQ^\top||$;
- $||Q^\top X - R||$.

**Suggestions:** look at the help of the function np.*linalg*.**norm** to compute the norm of an array.

In [2]:
def gramschmidt(X):
    """
    Function that performs the Gram-Schmidt method for a given square Matrix (changing the code is generalizable to
    rectangular matrices)
    The matrix must have full rank.
    :param X: square matrix represented as 2D-array object (numpy ndarray);
    :return Q: 2D-array (orthogonal matrix) 
    :return R: 2D-array (upper triangle matrix).
    :return Qqual: norm ||In - Q @ Q.T||
    :return QRqual: norm ||Q.T @ X - R||
    """

    m, n = X.shape # dimensioni della matrice di input
    
    if m != n:
        print('MATRIX IS NOT SQUARE!')
        return None, None, None, None
    
    # Initialization of the matrices
    R = np.zeros((m,n)) 
    Q = np.zeros((m,n)) 

    # primo vettore
    R[0, 0] = np.linalg.norm(X[:,0]) # norma della prima colonna
    Q[:, 0] = X[:, 0].copy() / R[0,0] # normalizzo la prima colonna per ottenere il primo vettore ortonormale

    for j in range(1, n): # ciclo sulle colonne successive da ortogonalizzare
        Q[:,j] = X[:,j].copy() # initialize comulmn j of Q # copio la j colonna da proiettare
        
        for i in range(0, j): # ciclo sugli indici delle righe
            R[i,j] = X[:,j] @ Q[:,i] # calcolo il coefficiente di proiezione
            Q[:, j] -= R[i,j] * Q[:,i] # sottraggo la componente lungo Q[:,i]
            
        R[j, j] = np.linalg.norm(Q[:,j]) # norma del vettore residuo
        Q[:,j] = Q[:,j]/R[j,j] # normalizzo
        
    Qqual = np.linalg.norm(np.identity(n) - Q @ Q.T) # misura di ortogonalità, dovrebbe essere vicino a zero 
    
    QRqual = np.linalg.norm(Q.T @ X - R)  # verifica fattorizzazione X=QR e dovrebbe essere vicino a zero

    return Q, R, Qqual, QRqual

In [3]:
# GRAM-SCHMIDT METHOD TEST

print('********** Running GS on A1...')
Q, R, Qqual, QRqual = gramschmidt(A1)
print('')

print('********** Matrix Q of A1 **********')
print(Q)
print('')
print(f'********** "Orthogonal Quality" of Q: {Qqual}')
print('')

print('********** Matrix R of A1 **********')
print(R)
print('')
print(f'********** "Factorization Quality" of Q @ R: {QRqual}')
print('')

print('********** Running GS on Ab1...')
_, _, _, _ = gramschmidt(Ab1)

********** Running GS on A1...

********** Matrix Q of A1 **********
[[ 0.4207029   0.02549469  0.86485754  0.27272795]
 [ 0.5224126   0.45265446 -0.03993905 -0.72152193]
 [ 0.20508173  0.70227294 -0.31166124  0.60631797]
 [ 0.71276618 -0.54887766 -0.39152725  0.19340138]]

********** "Orthogonal Quality" of Q: 4.982028949935843e-16

********** Matrix R of A1 **********
[[1.337821   1.46826719 1.08834065 0.54665771]
 [0.         0.46846699 0.2219623  0.51307049]
 [0.         0.         0.33397603 0.47726764]
 [0.         0.         0.         0.46375911]]

********** "Factorization Quality" of Q @ R: 3.6695978468454605e-16

********** Running GS on Ab1...
MATRIX IS NOT SQUARE!


### The Modified GS Method

The **Modified Gram-Schmidt** method is introduced for numerical applications because, in finite arithmetic, it is more stable than the classic method.

In exact arithmetic, the Modified GS method returns the same result of the GS method.

The Modified GS method, changes the operations in this way:
1. **for** $j=1,\ldots , n$ **do:**
    1. $\boldsymbol{q}_j\gets \boldsymbol{q}_j - (\boldsymbol{q}_j,\boldsymbol{q}_i) \boldsymbol{q}_i$, iteratively for each $i=1,\ldots, j-1$, where$(\boldsymbol{q}_j,\boldsymbol{q}_i)$ becomes $r_{ij}$;
    1. $\boldsymbol{q}_j\gets \frac{\boldsymbol{q}_j}{||\boldsymbol{q}_j||}$, where $||\boldsymbol{q}_j||$ becomes $r_{jj}$.

#### Exercise 2: Modified GS Method

Complete the function in the following cell, such that it performs the Modified GS method for any square matrix.

In [4]:
def mod_gramschmidt(X):
    """
    Function that performs the Modified Gram-Schmidt method for a given square Matrix (changing the code is
    generalizable to rectangular matrices)
    The matrix must have full rank.
    :param X: square matrix represented as 2D-array object (numpy ndarray);
    :return Q: 2D-array (orthogonal matrix) 
    :return R: 2D-array (upper triangle).
    :return Qqual: norm ||In - Q @ Q.T||
    :return QRqual: norm ||Q.T @ X - R||
    """

    m, n = X.shape
    
    # verifico la shape
    if m != n:
        print('MATRIX IS NOT SQUARE!')
        return None, None, None, None

    # inizializzo R e Q
    R = np.zeros((n,n))  
    Q = np.zeros((m,n))  

    # primo vettore
    R[0, 0] = np.linalg.norm(X[:,0]) # calcolo la norma della prima colonna 
    Q[:, 0] = X[:, 0].copy() / R[0,0] # normalizzo

    for j in range(1, n):
        Q[:,j] = X[:,j].copy()
        
        for i in range(0, j):
            # gni volta metto via la componente lungo il già ottenuto q_i, aggiornando il residuo. 
            # È più stabile numericamente del Gram–Schmidt classico.
            R[i,j] = Q[:,j] @ Q[:,i]
            Q[:, j] -= (R[i,j])*Q[:,i]
            
        R[j, j] = np.linalg.norm(Q[:,j])
        Q[:,j] = Q[:,j]/R[j,j]
        
    Qqual = np.linalg.norm(np.identity(n) - Q @ Q.T)  
    
    QRqual = np.linalg.norm(Q.T @ X - R) 

    return Q, R, Qqual, QRqual

In [5]:
# MODIFIED GRAM-SCHMIDT METHOD TEST

print('********** Running GS on A1...')
Q, R, Qqual, QRqual = mod_gramschmidt(A1)
print('')

print('********** Matrix Q of A1 **********')
print(Q)
print('')
print(f'********** "Orthogonal Quality" of Q: {Qqual}')
print('')

print('********** Matrix R of A1 **********')
print(R)
print('')
print(f'********** "Factorization Quality" of Q @ R: {QRqual}')
print('')

print('********** Running GS on Ab1...')
_, _, _, _ = mod_gramschmidt(Ab1)

********** Running GS on A1...

********** Matrix Q of A1 **********
[[ 0.4207029   0.02549469  0.86485754  0.27272795]
 [ 0.5224126   0.45265446 -0.03993905 -0.72152193]
 [ 0.20508173  0.70227294 -0.31166124  0.60631797]
 [ 0.71276618 -0.54887766 -0.39152725  0.19340138]]

********** "Orthogonal Quality" of Q: 4.3707157578031284e-16

********** Matrix R of A1 **********
[[1.337821   1.46826719 1.08834065 0.54665771]
 [0.         0.46846699 0.2219623  0.51307049]
 [0.         0.         0.33397603 0.47726764]
 [0.         0.         0.         0.46375911]]

********** "Factorization Quality" of Q @ R: 4.898901281322673e-16

********** Running GS on Ab1...
MATRIX IS NOT SQUARE!


## The Givens Method

The Givens (G) method takes into account the rotation matrices $G((h, k);X)$ that **set to zero** the $(h, k)$-th element of the matrix returned by the product $G((h,k);X) \, X$. Therefore, the Givens method consists in *setting to zero, one by one, all the elements under the diagonal* using the rotation matrices and, at the same time, obtaining an orthogonal matrix.

More precisely, given a square matrix $X\in\mathbb{R}^{n\times n}$, the method computes iteratively a matrix $Q$, through a product of rotation matrices, such that:
- $Q$ is orthogonal (i.e., $QQ^\top = \mathbb{I}_n = Q^{\top}Q$);
- The columns $\{\boldsymbol{q}_1,\ldots ,\boldsymbol{q}_n\}$ of $Q$ are an orthonormal base of the space $\langle \boldsymbol{x}_1,\ldots ,\boldsymbol{x}_n\rangle$ generated by the columns of $X$;
- $QX =: R\in\mathbb{R}^{n\times n}$ is an upper triangular matrix;

**N.B.:** if we want to preserve the same notation of the GS method, then G computes the matrix $Q^{\top}$ (such that $R=Q^\top X$ and, therefore, $QR=X$).

#### Rotation Matrices of the Givens Method (Case $h>k$)

The elements elements $g_{ij}:=G_{ij}((h,k); X)$ of a *Givens matrix* are defined as
$$
g_{ij}=
\begin{cases}
1\,,\quad & \text{if }i=j\neq h,k\\
c\,,\quad & \text{if }i=j= h,k\\
s\,,\quad & \text{if }i=k, j=h\\
-s\,,\quad & \text{if }i=h, j=k\\
0\,,\quad & \text{otherwise}\\
\end{cases}\,,
$$
where
$$
c:=\frac{x_{kk}}{\sqrt{x_{kk}^2 + x_{hk}^2}}\,,\quad s:=\frac{x_{hk}}{\sqrt{x_{kk}^2 + x_{hk}^2}}\,.
$$

Then, for the case $h>k$, the matrix has the following aspect:
$$
G((h,k);X) = 
\begin{bmatrix}
1 &    &    &    &    &    &    &    &    &    &    \\
    & \ddots &    &    &    &    &    &    &    &    &    \\
    & \quad & 1 &    &    &    &    &    &    &    &    &    \\
    &    &    & c & \cdots &    & \cdots & s &    &    &    \\
    &    &    & \vdots & 1 &    &    & \vdots &    &    &    \\
    &    &    &    &    & \ddots &    &    &    &    &    \\
    &    &    & \vdots &    &    & 1 & \vdots &    &    &    \\
    &    &    & -s & \cdots &    & \cdots & c &    &    &    \\
    &    &    &    &    &    &    &    & 1 &    &    &    \\
    &    &    &    &    &    &    &    &    & \ddots &    \\
    &    &    &    &    &    &    &    &    &    & 1 \\
\end{bmatrix}\,.
$$

#### Description of the G Method

From a "pseudocode point-of-view", given a square matrix $X\in\mathbb{R}^{n\times n}$, the algorithm performs the following operations:
1. $R\gets X$;
1. *initialization of* $Q$ (**exercise**)
1. **for** $k=1,\ldots ,n$ and $h=k+1, \ldots, n$ **do:** ($k$ for columns, $h$ for "under-diag." rows)
    1. $G\gets G((h, k); R)$
    1. *update* $Q$ (**exercise**)
    1. $R\gets GR$
1. **return** $Q$, $R$

#### Exercise 3: Givens Matrix

Complete the function in the following cell, such that it computes the Givens matrix $G((h,k); X)\in\mathbb{R}^{n\times n}$ for any square matrix $X\in\mathbb{R}^{n\times n}$ and any $h,k\in\{1,\ldots ,n\}$.

**Suggestions:** look at the help of the function np.**hypot** to compute the denominators of $c$ and $s$. Indeed, this function is better (from a numerical point of view) than using np.**sqrt** on the sum of $x_{kk}^2$ and $x_{hk}^2$.

In [6]:
def givens_mat(X, h, k):
    """
    Function that compute the Givens matrix for a given square matrix X and with respect to row h and column k
    :param X: square matrix represented as 2D-array object (numpy ndarray);
    :param h: integer value in the range of the number of X's rows;
    :param k: integer value in the range of the number of X's columns;
    :return G: the Givens matrix as 2D-array object (numpy ndarray).
    """
    
    m, n = X.shape
    
    if m != n:
        print('MATRIX IS NOT SQUARE!')
        return None
    
    # d (denominator of both c and s) can be written as:
    # d = np.sqrt(X[k, k]**2 + X[h, k]**2)
    # But is better (due to numerical problems) to use the hypot function.
    d = np.hypot(X[k,k], X[h,k]) 
    
    c = X[k,k] / d  
    s = X[h,k] / d 

    G = np.identity(n)
    G[h,h] = c
    G[k,k] = c
    G[h,k] = -s
    G[k,h] = s

    return G

In [7]:
# GIVENS MATRIX TEST

h, k = 1, 0
tolG = 1e-8

G_hk = givens_mat(A1, h, k)
G_hk_A1 = G_hk @ A1
G_hk_A1_tol = G_hk_A1.copy()
G_hk_A1_tol[abs(G_hk_A1_tol) < tolG] = 0

print('********** h, k **********')
print(f'h = {h} (row index)')
print(f'k = {k} (column index)')
print('')

print('********** Matrix G_hk **********')
print(G_hk)
print('')

print('********** Matrix G_hk @ A1 ((h,k)-th element should be zero) **********')
print('********** Original G_hk @ A1')
print(G_hk_A1)
print('')
print('********** "Rounded" G_hk @ A1')
print(G_hk_A1_tol)
print('')

********** h, k **********
h = 1 (row index)
k = 0 (column index)

********** Matrix G_hk **********
[[ 0.62721247  0.7788482   0.          0.        ]
 [-0.7788482   0.62721247  0.          0.        ]
 [ 0.          0.          1.          0.        ]
 [ 0.          0.          0.          1.        ]]

********** Matrix G_hk @ A1 ((h,k)-th element should be zero) **********
********** Original G_hk @ A1
[[ 8.97343719e-01  1.15748922e+00  9.82582939e-01  6.18522714e-01]
 [ 3.11688624e-17  1.23700595e-01 -1.74719979e-01 -5.06343189e-01]
 [ 2.74362649e-01  6.30106471e-01  2.74989520e-01  6.04864689e-01]
 [ 9.53553566e-01  7.89400137e-01  5.23141546e-01  1.08545651e-02]]

********** "Rounded" G_hk @ A1
[[ 0.89734372  1.15748922  0.98258294  0.61852271]
 [ 0.          0.12370059 -0.17471998 -0.50634319]
 [ 0.27436265  0.63010647  0.27498952  0.60486469]
 [ 0.95355357  0.78940014  0.52314155  0.01085457]]



#### Exercise 4: Givens Method

Complete the function in the following cell, such that it performs the Givens method for any square matrix. The function must return not only $Q$ and $R$, but also the following norms representing the quality of the outputs:
- $||\mathbb{I}_n - QQ^\top||$;
- $||Q X - R||$.

**Suggestions:** exploit the **givens_mat** function of the previous exercise.

In [16]:
def givens(X):
    """
    Function that performs the Givens method for a given square matrix X.
    :param X: square matrix represented as 2D-array object (numpy ndarray);
    :return Q: 2D-array (orthogonal matrix) 
    :return R: 2D-array (upper triangle).
    :return Qqual: norm ||In - Q @ Q.T||
    :return QRqual: norm ||Q @ X - R||
    """
    
    m, n = X.shape

    # verifica della dimensione della matrice
    if m != n:
        print('MATRIX IS NOT SQUARE!')
        return None, None, None, None
    
    # Initialization of the matrices
    R = X.copy()  # R diventerà triangolare superiore tramite rotazioni
    Q = np.identity(n)  # Q accumulerà le rotazioni in modo da diventare la Q ortogonale

    # ciclo sulle colonne: per ogni colonna j voglio azzerare gli elementi sotto la diagonale
    for j in range(n):
        for i in range(j+1, m): # per ogni riga i sotto la diagonale (i = j+1 ... m-1)
            G = givens_mat(R, i, j) # # costruisco la matrice di Givens che annulla R[i, j]
            Q = Q@G.T # aggiorno Q in modo che alla fine Q @ R == X (Q è ortogonale)
            # nota: uso Q = Q @ G.T per accumulare le rotazioni in modo che Q sia la Q "classica"
            # (se invece usassi Q = G @ Q, allora Q conterrebbe Q^T)
            R = G@R # applico la rotazione a R: ora l'elemento R[i,j] sarà (quasi) zero
            
            
    Qqual = np.linalg.norm(np.identity(n) - Q @ Q.T)  
    
    QRqual = np.linalg.norm(Q.T @ X - R)

    return Q, R, Qqual, QRqual

In [17]:
# GIVENS METHOD TEST

print('********** Running G on A1...')
print('')

Q, R, Qqual, QRqual = givens(A1)

tolR = 1e-8
Rtol = R.copy()
Rtol[abs(Rtol) < tolR] = 0



print('********** Matrix Q of A1 **********')
print(Q)
print('')
print(f'********** "Orthogonal Quality" of Q: {Qqual}')
print('')

print('********** Matrix R of A1 **********')
print('********** Original R')
print(R)
print('')
print('********** "Rounded" R')
print(Rtol)
print('')

print(f'********** "Factorization Quality" of Q.T @ R: {QRqual}')
print('')

print('********** Running G on Ab1...')
_, _, _, _ = givens(Ab1)

********** Running G on A1...

********** Matrix Q of A1 **********
[[ 0.4207029   0.02549469  0.86485754  0.27272795]
 [ 0.5224126   0.45265446 -0.03993905 -0.72152193]
 [ 0.20508173  0.70227294 -0.31166124  0.60631797]
 [ 0.71276618 -0.54887766 -0.39152725  0.19340138]]

********** "Orthogonal Quality" of Q: 5.481179523868196e-16

********** Matrix R of A1 **********
********** Original R
[[ 1.33782100e+00  1.46826719e+00  1.08834065e+00  5.46657709e-01]
 [ 4.44405925e-17  4.68466992e-01  2.21962299e-01  5.13070492e-01]
 [ 5.64638737e-18 -7.11523506e-18  3.33976031e-01  4.77267638e-01]
 [-3.51583722e-17  1.47292650e-17 -5.72534077e-18  4.63759106e-01]]

********** "Rounded" R
[[1.337821   1.46826719 1.08834065 0.54665771]
 [0.         0.46846699 0.2219623  0.51307049]
 [0.         0.         0.33397603 0.47726764]
 [0.         0.         0.         0.46375911]]

********** "Factorization Quality" of Q.T @ R: 4.801516808159076e-16

********** Running G on Ab1...
MATRIX IS NOT SQUARE!


## The Householder Method

The Householder (H) method takes into account a family of reflection matrices such that, for any vector $\boldsymbol{x}\in\mathbb{R}^m$, the reflection matrix w.r.t. $\boldsymbol{x}$ is a square matrix $P_{\boldsymbol{x}}\in\mathbb{R}^{m\times m}$ such that
$$
P_{\boldsymbol{x}}\boldsymbol{x} = 
\begin{bmatrix}
-\sigma\\
0\\
\vdots\\
0
\end{bmatrix}\,,
$$
where $\sigma = \mathrm{sign}(x_1)||\boldsymbol{x}||$.

Then, with the same idea of the Givens method, iteratively we **set to zero** all the elements under the diagonal of the given input square matrix $X\in\mathbb{R}^{n\times n}$, one column by one column, using the reflection matrices and, at the same time, obtaining an orthogonal matrix $Q$.

More precisely, given a square matrix $X\in\mathbb{R}^{n\times n}$, the method computes iteratively a matrix $Q\in\mathbb{R}^{n\times n}$, through a product of matrices with a block that is a reflection matrix in $\mathbb{R}^{m\times m}$. Specifically, the method returns $Q, R\in\mathbb{R}^{n\times n}$ such that:
- $Q$ is orthogonal (i.e., $QQ^\top = \mathbb{I}_n = Q^{\top}Q$);
- The columns $\{\boldsymbol{q}_1,\ldots ,\boldsymbol{q}_n\}$ of $Q$ are an orthonormal base of the space $\langle \boldsymbol{x}_1,\ldots ,\boldsymbol{x}_n\rangle$ generated by the columns of $X$;
- $QX =: R\in\mathbb{R}^{n\times n}$ is an upper triangular matrix;

**N.B.:** if we want to preserve the same notation of the GS method, then H (as G) computes the matrix $Q^{\top}$ (such that $R=Q^\top X$ and, therefore, $QR=X$).

#### Reflection Matrices of the Householder Method

Given a vector $\boldsymbol{x}\in\mathbb{R}^m$ its Householder matrix $P_{\boldsymbol{x}}\in\mathbb{R}^{m\times m}$ is defined as
$$
P_{\boldsymbol{x}} = \mathbb{I}_m - 2 \bar{\boldsymbol{u}}\bar{\boldsymbol{u}}^\top\,,
$$
where 
$$
\bar{\boldsymbol{u}} = \frac{\boldsymbol{u}}{||\boldsymbol{u}||}
\quad \text{and}\quad
\boldsymbol{u}:= \boldsymbol{x} + \sigma\boldsymbol{e}_1 = \boldsymbol{x} + \mathrm{sign}(x_1)||\boldsymbol{x}||\boldsymbol{e}_1\,.
$$

**Few Details:** $P_{\boldsymbol{x}}\boldsymbol{x}$ is the reflection of the vector $\boldsymbol{x}$ w.r.t. the hyperplane orthogonal to the versor $\bar{\boldsymbol{u}}$.

#### Description of the H Method

From a "pseudocode point-of-view", given a square matrix $X\in\mathbb{R}^{n\times n}$, the algorithm performs the following operations:
1. $R\gets X$;
1. *initialization of* $Q$ (**exercise**)
1. **for** $j=1,\ldots ,n$ **do:** ($j$ for columns)
    1. $\boldsymbol{x}\gets R_{j:n, j}$ (sub-column of $j$-th column, elements "from the diagonal to the end")
    1. $P_j\gets \begin{bmatrix} \mathbb{I}_{n-j} & \boldsymbol{0} \\ \boldsymbol{0} & P_{\boldsymbol{x}}\end{bmatrix}$ 
    1. *update* $Q$ (**exercise**)
    1. $R\gets P_jR$
1. **return** $Q$, $R$

#### Exercise 5: Householder Matrix

Complete the function in the following cell, such that it computes the Housholder matrix $P_{\boldsymbol{x}}\in\mathbb{R}^{m\times m}$ for any vector $\boldsymbol{x}\in\mathbb{R}^{m}$.

**Suggestions:** look at the help of the function np.**sign** to compute $\sigma$.

In [28]:
def householder_mat(x):
    """
    Function that compute the reflection matrix of the Householder method for a given vector x.
    :param x: vector that can be given both as 1D-array object and 2D-array column/row object (numpy ndarray);
    :return Px: Householder reflection matrix as 2D-array object (numpy ndarray).
    """
    
    # Reshaping the input as a column vector (if it is 1D-array or row 2D-array)... actually it works even if it is a non-vectot matrix...
    v = x.reshape(x.size, 1)
    
    sigma = np.sign(v[0][0]) * np.linalg.norm(v) 

    # Computation of u (versor)
    # oppure 
    # e1 = zeros(v.size, 1)
    # e1[0][0] = 1
    # u = v + sigma * e1
    u = v + sigma * np.eye(v.size, 1) # se uso size come dimensione della riga allora mi mette già il prodotto tipo 4*1=4 come dimensione della riga
    u_versor = u / np.linalg.norm(u)

    # Computation of the reflection matrix
    Px = np.identity(v.size) - 2*(u_versor*u_versor.T) # this product is a matrix 

    return Px

In [29]:
# HOUSEHOLDER MATRIX TEST

tolH = 1e-8

Pb1 = householder_mat(b1)
Pb1b1 = Pb1 @ b1
Pb1b1_tol = Pb1b1.copy()
Pb1b1_tol[abs(Pb1b1_tol) < tolH] = 0

print('********** Matrix Pb1 **********')
print(Pb1)
print('')

print('********** Matrix Pb1 @ b1 **********')
print('********** Original Pb1 @ b1')
print(Pb1b1)
print('')
print('********** "Rounded" Pb1 @ b1')
print(Pb1b1_tol)
print('')

********** Matrix Pb1 **********
[[-0.58083881 -0.53199851 -0.38003183 -0.48495326]
 [-0.53199851  0.82096693 -0.12789183 -0.16320096]
 [-0.38003183 -0.12789183  0.90864078 -0.11658221]
 [-0.48495326 -0.16320096 -0.11658221  0.85123109]]

********** Matrix Pb1 @ b1 **********
********** Original Pb1 @ b1
[[-4.69519437e+00]
 [-2.22044605e-16]
 [ 2.22044605e-16]
 [ 0.00000000e+00]]

********** "Rounded" Pb1 @ b1
[[-4.69519437]
 [ 0.        ]
 [ 0.        ]
 [ 0.        ]]



#### Exercise 4: Householder Method

Complete the function in the following cell, such that it performs the Householder method for any square matrix. The function must return not only $Q$ and $R$, but also the following norms representing the quality of the outputs:
- $||\mathbb{I}_n - QQ^\top||$;
- $||Q X - R||$.

**Suggestions:** exploit the **householder_mat** function of the previous exercise.


In [32]:
def householder(X):
    """
    Function that performs the Householder method for a given square matrix X.
    :param X: square matrix represented as 2D-array object (numpy ndarray);
    :return Q: 2D-array (orthogonal matrix) 
    :return R: 2D-array (upper triangle).
    :return Qqual: norm ||In - Q @ Q.T||
    :return QRqual: norm ||Q @ X - R||
    """
    
    m, n = X.shape
    
    if m != n:
        print('MATRIX IS NOT SQUARE!')
        return None, None, None, None
    
    # Initialization of the matrices
    R = X.copy()  # R diventerà triangolare superiore tramite rotazioni
    Q = np.identity(n)  # Q accumulerà le rotazioni in modo da diventare la Q ortogonale

    for j in range(n):
        Px = householder_mat(R[j:,j])
        Pj = np.identity(n)
        Pj[j:, j:] = Px
        
        # update of the matrices
        R = Pj @ R
        Q = Pj @ Q
    
    Qqual = np.linalg.norm(np.identity(n) - Q @ Q.T)  

    QRqual = np.linalg.norm(Q @ X - R) # non è più Q.T perchè in realtà nella mia Q c'è salavato il Q.T

    return Q, R, Qqual, QRqual

In [33]:
# HOUSEHOLDER METHOD TEST

print('********** Running H on A1...')
print('')

Q, R, Qqual, QRqual = householder(A1)

tolR = 1e-8
Rtol = R.copy()
Rtol[abs(Rtol) < tolR] = 0



print('********** Matrix Q of A1 **********')
print(Q)
print('')
print(f'********** "Orthogonal Quality" of Q: {Qqual}')
print('')

print('********** Matrix R of A1 **********')
print('********** Original R')
print(R)
print('')
print('********** "Rounded" R')
print(Rtol)
print('')

print(f'********** "Factorization Quality" of Q.T @ R: {QRqual}')
print('')

print('********** Running H on Ab1...')
_, _, _, _ = householder(Ab1)

********** Running H on A1...

********** Matrix Q of A1 **********
[[-0.4207029  -0.5224126  -0.20508173 -0.71276618]
 [-0.02549469 -0.45265446 -0.70227294  0.54887766]
 [ 0.86485754 -0.03993905 -0.31166124 -0.39152725]
 [ 0.27272795 -0.72152193  0.60631797  0.19340138]]

********** "Orthogonal Quality" of Q: 1.22450020355643e-15

********** Matrix R of A1 **********
********** Original R
[[-1.33782100e+00 -1.46826719e+00 -1.08834065e+00 -5.46657709e-01]
 [-2.65138377e-17 -4.68466992e-01 -2.21962299e-01 -5.13070492e-01]
 [-1.60063651e-16  2.77091915e-17  3.33976031e-01  4.77267638e-01]
 [-1.02066401e-16  9.35029853e-17  8.92239602e-17  4.63759106e-01]]

********** "Rounded" R
[[-1.337821   -1.46826719 -1.08834065 -0.54665771]
 [ 0.         -0.46846699 -0.2219623  -0.51307049]
 [ 0.          0.          0.33397603  0.47726764]
 [ 0.          0.          0.          0.46375911]]

********** "Factorization Quality" of Q.T @ R: 3.036065857770559e-16

********** Running H on Ab1...
MATRIX 

## A Comparison Between Methods


Let $V_n(\boldsymbol{x})\in\mathbb{R}^{m\times n}$ be the *Vandermonde* matrix of order $n$ w.r.t. the vector $\boldsymbol{x}\in\mathbb{R}^m$, i.e.:
$$
V_n(\boldsymbol{x}) = 
\begin{bmatrix}
x_1^0 & \cdots & x_1^{n-1} \\
\vdots &  & \vdots \\
x_m^0 & \cdots & x_m^{n-1} \\
\end{bmatrix}
$$

Considering only square Vandermonde matrices (i.e., $m=n$), study how the quality of the orthogonalization changes while increasing $n$ (and, consequently, the condition number $\kappa(V_n(\boldsymbol{x}))$). 

In particular, look at the quality measures returned by the methods and the corresponding plots.

#### Exercise 5: Methods and Performances

Complete the code in the following cell, such that it computes and illustrates how the norms $||\mathbb{I}_n - QQ^\top||$ and $||Q X - R||$ (or $||Q^{\top} X - R||$) changes with $n$

**Suggestions:** use the **vander** function for computing the Vandermonde matrix.


In [ ]:
n_values = [2 ** i for i in range(8)]

x = 2 * np.random.rand(n_values[-1])  # Uniform random values in [0, 2]

Qqual_df = pd.DataFrame(np.zeros((len(n_values), 4)), columns=['GS', 'mGS', 'G', 'H'], index=n_values)
QRqual_df = pd.DataFrame(np.zeros((len(n_values), 4)), columns=['GS', 'mGS', 'G', 'H'], index=n_values)

cond_values = []

for n in n_values:
    # Select the first n elements of x for building the order-n Vandermonde matrix
    xn = ...  # <-- TODO!
    V = np.vander(..., increasing=True)  # <-- TODO!
    
    cond_values.append(np.linalg.cond(V))

    # Compute the "quality norms" of the algorithms and store the results in the pandas DataFrame.
    # EXAMPLE for storing value in the pandas DataFrame for the case of GS method ("Qqual" norm):
    #     Qqual_df.loc[n, 'GS'] = Qqual_norm_GS
    #
    # ... <-- TODO!
    

print('******* "ORTHOGONAL QUALITY" OF Q *******')
display(Qqual_df)
print('')

print('******* "FACTORIZATION QUALITY" *******')
display(QRqual_df)
print('')


# ***************** FIGURE 0 *****************
fig0, ax0 = plt.subplots(1, 2, figsize=(10,5))
ax0[0].plot(n_values, cond_values, '-*', label='cond. num.')

ax0[1].plot(n_values, cond_values, '-*', label='cond. num.')

ax0[0].set_title('')
ax0[0].set_xlabel('order (n)')
ax0[0].set_ylabel('cond. num.')
ax0[0].grid()
ax0[0].legend()

ax0[1].set_title('LOG. SCALE')
ax0[1].set_xlabel('order (n)')
ax0[1].set_ylabel('cond. num.')
ax0[1].set_yscale(...)  # <-- TODO!
ax0[1].grid()
ax0[1].legend()

fig0.suptitle('V_n(x) Condition Number') 


# ***************** FIGURE 1 *****************
fig1, ax1 = plt.subplots(1, 2, figsize=(10, 5))

ax1[0].plot(..., '--x', label=...)  # <-- TODO!
...  # <-- TODO!


ax1[1].plot(..., '--x', label=...) # <-- TODO!
...  # <-- TODO!

ax1[0].set_title('||I_n - Q @ Q.T||')
ax1[0].set_xlabel('order (n)')
ax1[0].set_ylabel('norm value')
ax1[0].grid()
ax1[0].legend()

ax1[1].set_title('||Q @ X - R|| or ||Q.T @ X - R||')
ax1[1].set_xlabel('order (n)')
ax1[1].set_ylabel('norm value')
ax1[1].grid()
ax1[1].legend()

fig1.suptitle('ORTHOGONALIZATION QUALITY') 


# ***************** FIGURE 2 *****************
fig2, ax2 = plt.subplots(1, 2, figsize=(10, 5))

ax2[0].plot(..., '--x', label=...)  # <-- TODO!
...  # <-- TODO!


ax2[1].plot(..., '--x', label=...) # <-- TODO!
...  # <-- TODO!

ax2[0].set_title('||I_n - Q @ Q.T||')
ax2[0].set_xlabel('order (n)')
ax2[0].set_ylabel('norm value')
ax2[0].set_yscale(...)  # <-- TODO!
ax2[0].grid()
ax2[0].legend()

ax2[1].set_title('||Q @ X - R|| or ||Q.T @ X - R||')
ax2[1].set_xlabel('order (n)')
ax2[1].set_ylabel('norm value')
ax2[1].set_yscale(...)  # <-- TODO!
ax2[1].grid()
ax2[1].legend()

fig2.suptitle('ORTHOGONALIZATION QUALITY (LOG. SCALE)') 
    
    